branches:
    only:
        - devel
dist: xenial
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  verbose: true
  target_branch: master
  local-dir: public
  on:
    branch: devel

services:
  - docker

script:
  - docker pull alpine
  - docker run -v $(pwd):/build alpine /bin/sh -c "apk add --no-cache hugo; cd build; hugo"
